### ISSUE TITLE
Set up a CSS preprocessor

### ISSUE THREAD

**Issue by elischutze** [elischutze/grrrrl#3]
Start using sass! 
- [x] make some scss files 
- [x] organise the directory and document what command to run to turn into css
- [x] set some variables for main fonts and colors (pick a google font!)

**Comment by criptodev** [comment]
This is ok?. Im going to merge into the project.
![screenshot from 2017-01-05 09-28-42](https://cloud.githubusercontent.com/assets/18405453/21682151/6230e444-d329-11e6-87b3-83467ad03ac4.jpg)

**Comment by criptodev** [comment]
Its ok to use sass instead of scsss?. I can change that.

**Comment by elischutze** [comment]
I'd prefer scss but the rest seems fine!

**Comment by criptodev** [comment]
Its done : )
